version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "/code/PurviewAutomation"
    schedule:
      interval: "weekly"
      day: "sunday"
